// export const languagesList = [
//   { "label": "Afar", "lang": "aa" },
//   { "label": "Avestan", "lang": "ae" },
//   { "label": "Afrikaans", "lang": "af" },
//   { "label": "Akan", "lang": "ak" },
//   { "label": "Amharic", "lang": "am" },
//   { "label": "Arabic", "lang": "ar" },
//   { "label": "Azerbaijani", "lang": "az" },
//   { "label": "Belarusian", "lang": "be" },
//   { "label": "Bulgarian", "lang": "bg" },
//   { "label": "Bambara", "lang": "bm" },
//   { "label": "Kazakh", "lang": "kk" },
//   { "label": "Bislama", "lang": "bi" },
//   { "label": "Bengali", "lang": "bn" },
//   { "label": "Tibetan", "lang": "bo" },
//   { "label": "Bosnian", "lang": "bs" },
//   { "label": "Czech", "lang": "cs" },
//   { "label": "Danish", "lang": "da" },
//   { "label": "German", "lang": "de" },
//   { "label": "Divehi", "lang": "dv" },
//   { "label": "Dzongkha", "lang": "dz" },
//   { "label": "Greek", "lang": "el" },
//   { "label": "English", "lang": "en" },
//   { "label": "Spanish", "lang": "es" },
//   { "label": "Spanish (Mexico)", "lang": "es-mx" },
//   { "label": "Estonian", "lang": "et" },
//   { "label": "Persian", "lang": "fa" },
//   { "label": "Finnish", "lang": "fi" },
//   { "label": "Fijian", "lang": "fj" },
//   { "label": "Faroese", "lang": "fo" },
//   { "label": "French", "lang": "fr" },
//   { "label": "Irish", "lang": "ga" },
//   { "label": "Guarani", "lang": "gn" },
//   { "label": "Hebrew", "lang": "he" },
//   { "label": "Hindi", "lang": "hi" },
//   { "label": "Hiri Motu", "lang": "ho" },
//   { "label": "Croatian", "lang": "hr" },
//   { "label": "Haitian", "lang": "ht" },
//   { "label": "Hungarian", "lang": "hu" },
//   { "label": "Armenian", "lang": "hy" },
//   { "label": "Indonesian", "lang": "id" },
//   { "label": "Icelandic", "lang": "is" },
//   { "label": "Italian", "lang": "it" },
//   { "label": "Japanese", "lang": "ja" },
//   { "label": "Georgian", "lang": "ka" },
//   { "label": "Kongo", "lang": "kg" },
//   { "label": "Korean", "lang": "ko" },
//   { "label": "Latin", "lang": "la" },
//   { "label": "Luxembourgish", "lang": "lb" },
//   { "label": "Lao", "lang": "lo" },
//   { "label": "Lithuanian", "lang": "lt" },
//   { "label": "Latvian", "lang": "lv" },
//   { "label": "Malagasy", "lang": "mg" },
//   { "label": "Marshallese", "lang": "mh" },
//   { "label": "Maori", "lang": "mi" },
//   { "label": "Macedonian", "lang": "mk" },
//   { "label": "Mongolian", "lang": "mn" },
//   { "label": "Malay", "lang": "ms" },
//   { "label": "Maltese", "lang": "mt" },
//   { "label": "Burmese", "lang": "my" },
//   { "label": "Nauru", "lang": "na" },
//   { "label": "Nepali", "lang": "ne" },
//   { "label": "Dutch", "lang": "nl" },
//   { "label": "Norwegian", "lang": "no" },
//   { "label": "Polish", "lang": "pl" },
//   { "label": "Portuguese", "lang": "pt" },
//   { "label": "Romanian", "lang": "ro" },
//   { "label": "Russian", "lang": "ru" },
//   { "label": "Kinyarwanda", "lang": "rw" },
//   { "label": "Sindhi", "lang": "sd" },
//   { "label": "Slovak", "lang": "sk" },
//   { "label": "Slovenian", "lang": "sl" },
//   { "label": "Somali", "lang": "so" },
//   { "label": "Albanian", "lang": "sq" },
//   { "label": "Serbian", "lang": "sr" },
//   { "label": "Swedish", "lang": "sv" },
//   { "label": "Swahili", "lang": "sw" },
//   { "label": "Tajik", "lang": "tg" },
//   { "label": "Thai", "lang": "th" },
//   { "label": "Tigrinya", "lang": "ti" },
//   { "label": "Turkmen", "lang": "tk" },
//   { "label": "Turkish", "lang": "tr" },
//   { "label": "Ukrainian", "lang": "uk" },
//   { "label": "Uzbek", "lang": "uz" },
//   { "label": "Vietnamese", "lang": "vi" },
//   { "label": "Chinese", "lang": "zh" },
// ];

// hardcoded based on the languagesList
export const languagesIsoCodesMap = {
  'aa': 'Afar',
  'ae': 'Avestan',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'Amharic',
  'ar': 'Arabic',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bm': 'Bambara',
  'kk': 'Kazakh',
  'bi': 'Bislama',
  'bn': 'Bengali',
  'bo': 'Tibetan',
  'bs': 'Bosnian',
  'cs': 'Czech',
  'da': 'Danish',
  'de': 'German',
  'dv': 'Divehi',
  'dz': 'Dzongkha',
  'el': 'Greek',
  'en': 'English',
  'es': 'Spanish',
  'es-mx': 'Spanish (Mexico)',
  'et': 'Estonian',
  'fa': 'Persian',
  'fi': 'Finnish',
  'fj': 'Fijian',
  'fo': 'Faroese',
  'fr': 'French',
  'ga': 'Irish',
  'gn': 'Guarani',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'ho': 'Hiri Motu',
  'hr': 'Croatian',
  'ht': 'Haitian',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'is': 'Icelandic',
  'it': 'Italian',
  'ja': 'Japanese',
  'ka': 'Georgian',
  'kg': 'Kongo',
  'ko': 'Korean',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mg': 'Malagasy',
  'mh': 'Marshallese',
  'mi': 'Maori',
  'mk': 'Macedonian',
  'mn': 'Mongolian',
  'ms': 'Malay',
  'mt': 'Maltese',
  'my': 'Burmese',
  'na': 'Nauru',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'no': 'Norwegian',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'ro': 'Romanian',
  'ru': 'Russian',
  'rw': 'Kinyarwanda',
  'sd': 'Sindhi',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'tg': 'Tajik',
  'th': 'Thai',
  'ti': 'Tigrinya',
  'tk': 'Turkmen',
  'tr': 'Turkish',
  'uk': 'Ukrainian',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'zh': 'Chinese',
}

export type LanguageEnum = keyof typeof languagesIsoCodesMap;
